development:
  adapter: mysql
  database: movieme
  username: root
  password: 
  host: 127.0.0.1

test:
  adapter: mysql
  database: movieme_test
  username: root
  password: 
  host: 127.0.0.1

production:
  adapter: mysql
  database: movieme
  username: root
  password: anerian2009-rocks
  host: 127.0.0.1
