--- 
- :source: http://code.whytheluckystiff.net
  :version: = 0.6
  :name: hpricot
- :name: httparty
- :name: json
- :name: aws-s3
- :name: paperclip
- :name: chronic
- :version: 2.3.2
  :name: rails
